# Generated by Django 3.1.7 on 2021-03-27 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peaks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecasted_at', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('peak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peaks.peak')),
            ],
        ),
    ]
