# Generated by Django 3.1.7 on 2021-03-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peaks', '0003_peak_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peak',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='peak',
            name='longitude',
        ),
    ]
